### ISSUE TITLE
Question: how to compile proto without tonic's transport

### ISSUE THREAD

**Issue by rcarcasses** [devashishdxt/tonic-web-wasm-client#2]
Hi, thanks for sharing your hard work. I'm trying to compile/generate tonic's code with the transport feature disabled but no success so far. Concretely I have modified my `Cargo.toml` to conditionally compile the protos according to the target:

```toml
...
[build-dependencies]
prost-build = "0.10.4"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
tonic-build = "0.7"

[target.'cfg(target_arch = "wasm32")'.build-dependencies]
tonic-build = { version = "0.7", default-features = false, features = ["prost"]}

[dependencies]
prost = { version = "0.10" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic = { version = "0.7.2", default-features = false, features = ["codegen", "prost"]}
```

With this `cargo build` runs (I have a `build.rs` with some little configuration as expected), but when I try to target wasm with `cargo build --lib --target wasm32-unknown-unknown` it fails miserably.

Can you provide some hint please? Appreciated!
