### ISSUE TITLE
issues creating new client instance

### ISSUE THREAD

**Issue by borngraced** [devashishdxt/tonic-web-wasm-client#45]
I have my code setup correctly but creating new client `CompactTxStreamerClient` from `Client` results in an error.

weird because I confirm that this only works in the test_suite from the repo

```rust
fn build_client() -> CompactTxStreamerClient<Client> {
    let base_url = "http://localhost:50051".to_string();
    let wasm_client = Client::new(base_url);

    CompactTxStreamerClient::new(wasm_client.into())
}
```

ERROR 

```rust
the trait bound `Client: Service<request::Request<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, Status>>>` is not satisfied
the trait `Service<request::Request<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, tonic::status::Status>>>` is implemented for `Client`
required for `Client` to implement `GrpcService<http_body::combinators::box_body::UnsyncBoxBody<prost::bytes::Bytes, Status>>
```

**Comment by devashishdxt** [comment]
Thanks for creating this issue. Can you please mention the version of `tonic` and `tonic-web-wasm-client` that you're using?

**Comment by borngraced** [comment]
> Thanks for creating this issue. Can you please mention the version of `tonic` and `tonic-web-wasm-client` that you're using?

```toml
[dependencies]
prost = "0.12.1"
tonic = { version = "0.10.1", default-features = false, features = [
    "prost",
    "codegen",
] }
tonic-web-wasm-client = "0.4.0"
wasm-bindgen-test = "0.3.34"

[build-dependencies]
tonic-build = { version = "0.10.1", default-features = false, features = [
    "prost",
] }
```
